package com.example.audio

data class VocabularyItem(
    val word: String,
    val transcription: String = "",
    val meaningPt: String,
    val category: String = "Geral"
)

data class PhraseItem(
    val phrase: String,
    val pronunciation: String = "",
    val translationPt: String,
    val category: String = "Conversação"
)

data class LanguageStudyPack(
    val languageCode: String,
    val words: List<VocabularyItem>,
    val phrases: List<PhraseItem>
)

object LanguageLearningData {

    fun getStudyPack(langCode: String): LanguageStudyPack {
        val clean = langCode.trim().lowercase().split("-").first()
        return PACKS[clean] ?: defaultPack(clean)
    }

    private val PACKS = mapOf(
        "pt" to LanguageStudyPack(
            languageCode = "pt",
            words = listOf(
                VocabularyItem("Olá", "o-lá", "Cumprimento / Saudação", "Saudações"),
                VocabularyItem("Obrigado", "o-bri-ga-do", "Agradecimento (masculino)", "Cortesia"),
                VocabularyItem("Obrigada", "o-bri-ga-da", "Agradecimento (feminino)", "Cortesia"),
                VocabularyItem("Por favor", "por fa-vor", "Pedido cortês", "Cortesia"),
                VocabularyItem("Sim", "sim", "Afirmação", "Básico"),
                VocabularyItem("Não", "não", "Negação", "Básico"),
                VocabularyItem("Água", "á-gua", "Líquido essencial", "Comida & Bebida"),
                VocabularyItem("Pão", "pão", "Alimento básico", "Comida & Bebida"),
                VocabularyItem("Amigo", "a-mi-go", "Companheiro próximo", "Sociedade"),
                VocabularyItem("Família", "fa-mí-lia", "Parentes / Lar", "Sociedade"),
                VocabularyItem("Tempo", "tem-po", "Clima ou duração", "Natureza"),
                VocabularyItem("Trabalho", "tra-ba-lho", "Emprego / Profissão", "Sociedade"),
                VocabularyItem("Cidade", "ci-da-de", "Centro urbano", "Locais"),
                VocabularyItem("Mundo", "mun-do", "Planeta Terra", "Geral"),
                VocabularyItem("Coração", "co-ra-ção", "Órgão / Sentimento", "Corpo"),
                VocabularyItem("Música", "mú-si-ca", "Arte sonora", "Cultura"),
                VocabularyItem("Noite", "noi-te", "Período escuro", "Tempo"),
                VocabularyItem("Dia", "di-a", "Período com sol", "Tempo"),
                VocabularyItem("Amor", "a-mor", "Afeto profundo", "Sentimentos"),
                VocabularyItem("Paz", "paz", "Harmonia e tranquilidade", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("Bom dia, como está?", "bom di-a co-mo es-tá", "Cumprimento matinal"),
                PhraseItem("Boa tarde a todos.", "boa tar-de a to-dos", "Cumprimento vespertino"),
                PhraseItem("Boa noite e bons sonhos.", "boa noi-te e bons so-nhos", "Despedida noturna"),
                PhraseItem("Muito prazer em conhecê-lo.", "mui-to pra-zer em co-nhe-cê-lo", "Ao conhecer alguém"),
                PhraseItem("Onde fica o centro da cidade?", "on-de fi-ca o cen-tro", "A pedir direções"),
                PhraseItem("Quanto custa este produto?", "quan-to cus-ta es-te pro-du-to", "Em compras"),
                PhraseItem("Pode ajudar-me, por favor?", "po-de a-ju-dar-me", "A pedir auxílio"),
                PhraseItem("Não falo muito bem este idioma.", "não fa-lo mui-to bem", "Comunicação"),
                PhraseItem("Pode falar um pouco mais devagar?", "po-de fa-lar mais de-va-gar", "Compreensão"),
                PhraseItem("A comida está deliciosa!", "a co-mi-da es-tá de-li-cio-sa", "No restaurante"),
                PhraseItem("Gostaria de pedir a conta, por favor.", "gos-ta-ri-a de pe-dir a con-ta", "No restaurante"),
                PhraseItem("Que horas são neste momento?", "que ho-ras são nes-te mo-men-to", "A perguntar a hora"),
                PhraseItem("Está um dia lindo e ensolarado.", "es-tá um di-a lin-do", "Sobre o tempo"),
                PhraseItem("Onde posso encontrar uma farmácia?", "on-de pos-so en-con-trar", "Emergência"),
                PhraseItem("Estou perdido, preciso de orientação.", "es-tou per-di-do", "Emergência"),
                PhraseItem("Muito obrigado pela sua gentileza.", "mui-to o-bri-ga-do pe-la gen-ti-le-za", "Gratidão"),
                PhraseItem("Tenha um excelente fim de semana.", "te-nha um ex-ce-len-te fim de se-ma-na", "Desejos"),
                PhraseItem("Até logo e cuide-se bem.", "a-té lo-go e cui-de-se", "Despedida"),
                PhraseItem("Tudo vai correr pelo melhor.", "tu-do vai cor-rer bem", "Encorajamento"),
                PhraseItem("A inteligência artificial conecta o mundo.", "a in-te-li-gên-cia ar-ti-fi-ci-al co-nec-ta", "Tecnologia")
            )
        ),

        "es" to LanguageStudyPack(
            languageCode = "es",
            words = listOf(
                VocabularyItem("Hola", "o-la", "Olá", "Saudações"),
                VocabularyItem("Gracias", "gra-cias", "Obrigado", "Cortesia"),
                VocabularyItem("Por favor", "por fa-vor", "Por favor", "Cortesia"),
                VocabularyItem("Amigo", "a-mi-go", "Amigo", "Sociedade"),
                VocabularyItem("Familia", "fa-mi-lia", "Família", "Sociedade"),
                VocabularyItem("Comida", "co-mi-da", "Comida", "Alimentação"),
                VocabularyItem("Agua", "a-gua", "Água", "Alimentação"),
                VocabularyItem("Tiempo", "tiem-po", "Tempo", "Natureza"),
                VocabularyItem("Trabajo", "tra-ba-jo", "Trabalho", "Sociedade"),
                VocabularyItem("Ciudad", "ciu-dad", "Cidade", "Locais"),
                VocabularyItem("Noche", "no-che", "Noite", "Tempo"),
                VocabularyItem("Mañana", "ma-ña-na", "Amanhã / Manhã", "Tempo"),
                VocabularyItem("Corazón", "co-ra-zón", "Coração", "Corpo"),
                VocabularyItem("Sol", "sol", "Sol", "Natureza"),
                VocabularyItem("Mundo", "mun-do", "Mundo", "Geral"),
                VocabularyItem("Calle", "ca-lle", "Rua", "Locais"),
                VocabularyItem("Dinero", "di-ne-ro", "Dinheiro", "Economia"),
                VocabularyItem("Viaje", "via-je", "Viagem", "Lazer"),
                VocabularyItem("Hermoso", "her-mo-so", "Belo / Lindo", "Adjetivos"),
                VocabularyItem("Paz", "paz", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("¡Hola! ¿Cómo estás?", "o-la co-mo es-tas", "Olá! Como estás?"),
                PhraseItem("Buenos días a todos.", "bue-nos di-as", "Bom dia a todos."),
                PhraseItem("Buenas tardes, un placer.", "bue-nas tar-des", "Boa tarde, um prazer."),
                PhraseItem("Buenas noches y hasta mañana.", "bue-nas no-ches", "Boa noite e até amanhã."),
                PhraseItem("Mucho gusto en conocerte.", "mu-cho gus-to", "Muito gosto em conhecer-te."),
                PhraseItem("¿Dónde está la estación de tren?", "don-de es-ta la es-ta-cion", "Onde fica a estação de comboios?"),
                PhraseItem("¿Cuánto cuesta esto, por favor?", "cuan-to cues-ta es-to", "Quanto custa isto, por favor?"),
                PhraseItem("¿Puedes ayudarme un momento?", "pue-des a-yu-dar-me", "Podes ajudar-me um momento?"),
                PhraseItem("No hablo español con fluidez.", "no ha-blo es-pa-ñol", "Não falo espanhol com fluência."),
                PhraseItem("¿Podrías hablar más despacio?", "po-dri-as ha-blar mas des-pa-cio", "Poderias falar mais devagar?"),
                PhraseItem("La comida está realmente exquisita.", "la co-mi-da es-ta ex-qui-si-ta", "A comida está realmente deliciosa."),
                PhraseItem("La cuenta, por favor.", "la cuen-ta por fa-vor", "A conta, por favor."),
                PhraseItem("¿Qué hora tienes ahora mismo?", "que ho-ra tie-nes", "Que horas tens neste momento?"),
                PhraseItem("Hace un día muy soleado y agradable.", "ha-ce un di-a so-lea-do", "Está um dia muito ensolarado."),
                PhraseItem("Busco una farmacia de guardia.", "bus-co u-na far-ma-cia", "Procuro uma farmácia de serviço."),
                PhraseItem("Estoy perdido, ¿me indica el camino?", "es-toy per-di-do", "Estou perdido, indica-me o caminho?"),
                PhraseItem("Muchas gracias por tu amabilidad.", "mu-chas gra-cias", "Muito obrigado pela tua amabilidade."),
                PhraseItem("¡Que tengas un buen fin de semana!", "que ten-gas un buen fin", "Tem um bom fim de semana!"),
                PhraseItem("¡Hasta luego y cuídate mucho!", "has-ta lue-go cui-da-te", "Até logo e cuida-te muito!"),
                PhraseItem("La tecnología rompe todas las barreras.", "la tec-no-lo-gia rom-pe ba-rre-ras", "A tecnologia quebra todas as barreiras.")
            )
        ),

        "fr" to LanguageStudyPack(
            languageCode = "fr",
            words = listOf(
                VocabularyItem("Bonjour", "bon-jour", "Bom dia / Olá", "Saudações"),
                VocabularyItem("Merci", "mer-ci", "Obrigado", "Cortesia"),
                VocabularyItem("S'il vous plaît", "sil-vou-plê", "Por favor", "Cortesia"),
                VocabularyItem("Oui", "ui", "Sim", "Básico"),
                VocabularyItem("Non", "non", "Não", "Básico"),
                VocabularyItem("Ami", "a-mi", "Amigo", "Sociedade"),
                VocabularyItem("Famille", "fa-miy", "Família", "Sociedade"),
                VocabularyItem("Eau", "ô", "Água", "Alimentação"),
                VocabularyItem("Pain", "pan", "Pão", "Alimentação"),
                VocabularyItem("Temps", "tan", "Tempo", "Natureza"),
                VocabularyItem("Travail", "tra-vay", "Trabalho", "Sociedade"),
                VocabularyItem("Ville", "vil", "Cidade", "Locais"),
                VocabularyItem("Nuit", "nüi", "Noite", "Tempo"),
                VocabularyItem("Monde", "mond", "Mundo", "Geral"),
                VocabularyItem("Cœur", "kœr", "Coração", "Corpo"),
                VocabularyItem("Soleil", "so-ley", "Sol", "Natureza"),
                VocabularyItem("Rue", "rü", "Rua", "Locais"),
                VocabularyItem("Argent", "ar-jan", "Dinheiro / Prata", "Economia"),
                VocabularyItem("Voyage", "vwa-yaj", "Viagem", "Lazer"),
                VocabularyItem("Paix", "pè", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("Bonjour, comment allez-vous ?", "bon-jour ko-man ta-lé vu", "Bom dia, como está?"),
                PhraseItem("Bonsoir à tout le monde.", "bon-swar a tu l'mond", "Boa noite a todos."),
                PhraseItem("Bonne nuit et faites de beaux rêves.", "bon nüi", "Boa noite e bons sonhos."),
                PhraseItem("Enchanté de faire votre connaissance.", "an-shan-té", "Muito prazer em conhecê-lo."),
                PhraseItem("Où se trouve la gare ?", "u s'truv la gar", "Onde fica a estação ferroviária?"),
                PhraseItem("Combien coûte ceci, s'il vous plaît ?", "kon-byan kout s'si", "Quanto custa isto, por favor?"),
                PhraseItem("Pouvez-vous m'aider un instant ?", "pu-vé vu m'é-dé", "Pode ajudar-me um instante?"),
                PhraseItem("Je ne parle pas très bien français.", "j'ne parl pa tré byan fran-sé", "Não falo francês muito bem."),
                PhraseItem("Pourriez-vous parler plus lentement ?", "pu-ryé vu par-lé plü lan-t'man", "Poderia falar mais devagar?"),
                PhraseItem("Le repas est vraiment délicieux !", "l're-pa é vre-man dé-li-syeu", "A refeição está verdadeiramente deliciosa!"),
                PhraseItem("L'addition, s'il vous plaît.", "la-di-syon sil vu plé", "A conta, por favor."),
                PhraseItem("Quelle heure est-il maintenant ?", "kèl œur é-til", "Que horas são agora?"),
                PhraseItem("Il fait un temps magnifique aujourd'hui.", "il fè un tan ma-nyi-fik", "Está um tempo magnífico hoje."),
                PhraseItem("Où puis-je trouver une pharmacie ?", "u püij tru-vé ün far-ma-si", "Onde posso encontrar uma farmácia?"),
                PhraseItem("Je suis perdu, pouvez-vous m'indiquer ?", "j'sui pèr-dü", "Estou perdido, pode indicar-me?"),
                PhraseItem("Merci beaucoup pour votre aide précieuse.", "mèr-si bo-ku", "Muito obrigado pela sua valiosa ajuda."),
                PhraseItem("Passez un excellent week-end.", "pa-sé un èk-se-lan wik-end", "Tenha um excelente fim de semana."),
                PhraseItem("À bientôt et prenez bien soin de vous.", "a byan-to", "Até breve e cuide bem de si."),
                PhraseItem("Tout va très bien se passer.", "tu va tré byan s'pa-sé", "Tudo vai correr muito bem."),
                PhraseItem("La voix humaine unit les peuples.", "la vwa ü-mèn ü-ni lé pœpl", "A voz humana une os povos.")
            )
        ),

        "en" to LanguageStudyPack(
            languageCode = "en",
            words = listOf(
                VocabularyItem("Hello", "he-lo", "Olá", "Saudações"),
                VocabularyItem("Thank you", "thenk yu", "Obrigado", "Cortesia"),
                VocabularyItem("Please", "pliz", "Por favor", "Cortesia"),
                VocabularyItem("Yes", "yes", "Sim", "Básico"),
                VocabularyItem("No", "nou", "Não", "Básico"),
                VocabularyItem("Friend", "frend", "Amigo", "Sociedade"),
                VocabularyItem("Family", "fe-mi-li", "Família", "Sociedade"),
                VocabularyItem("Water", "wa-ter", "Água", "Alimentação"),
                VocabularyItem("Food", "fud", "Comida", "Alimentação"),
                VocabularyItem("Time", "taim", "Tempo / Hora", "Natureza"),
                VocabularyItem("Work", "werk", "Trabalho", "Sociedade"),
                VocabularyItem("City", "si-ti", "Cidade", "Locais"),
                VocabularyItem("Night", "nait", "Noite", "Tempo"),
                VocabularyItem("World", "werld", "Mundo", "Geral"),
                VocabularyItem("Heart", "hart", "Coração", "Corpo"),
                VocabularyItem("Sun", "san", "Sol", "Natureza"),
                VocabularyItem("Street", "strit", "Rua", "Locais"),
                VocabularyItem("Money", "ma-ni", "Dinheiro", "Economia"),
                VocabularyItem("Journey", "djer-ni", "Jornada / Viagem", "Lazer"),
                VocabularyItem("Peace", "pis", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("Hello! How are you today?", "he-lo hau ar yu", "Olá! Como está hoje?"),
                PhraseItem("Good morning everyone.", "gud mor-ning", "Bom dia a todos."),
                PhraseItem("Good evening, nice to see you.", "gud iv-ning", "Boa noite, bom ver-te."),
                PhraseItem("Good night and sweet dreams.", "gud nait", "Boa noite e doces sonhos."),
                PhraseItem("Nice to meet you.", "nais tu mit yu", "Muito prazer em conhecê-lo."),
                PhraseItem("Where is the nearest train station?", "wher iz the stei-shon", "Onde fica a estação mais próxima?"),
                PhraseItem("How much does this cost?", "hau match daz this kost", "Quanto custa isto?"),
                PhraseItem("Could you please help me?", "kud yu pliz help mi", "Poderia ajudar-me por favor?"),
                PhraseItem("I do not speak English very well.", "ai du not spik", "Não falo inglês muito bem."),
                PhraseItem("Could you speak a bit slower?", "kud yu spik slou-er", "Poderia falar um pouco mais devagar?"),
                PhraseItem("This food is delicious!", "this fud iz de-li-shas", "Esta comida está deliciosa!"),
                PhraseItem("May I have the bill, please?", "mei ai hav the bil", "Pode trazer a conta, por favor?"),
                PhraseItem("What time is it right now?", "what taim iz it", "Que horas são agora?"),
                PhraseItem("It is a beautiful sunny day.", "it iz a biu-ti-ful dei", "Está um belo dia ensolarado."),
                PhraseItem("Where can I find a pharmacy?", "wher ken ai faind a far-ma-si", "Onde posso encontrar uma farmácia?"),
                PhraseItem("I am lost, can you direct me?", "ai em lost", "Estou perdido, pode orientar-me?"),
                PhraseItem("Thank you very much for your kindness.", "thenk yu ve-ri match", "Muito obrigado pela sua gentileza."),
                PhraseItem("Have a wonderful weekend ahead.", "hav a won-der-ful wik-end", "Tenha um maravilhoso fim de semana."),
                PhraseItem("See you later and take good care.", "si yu lei-ter", "Até logo e cuide-se bem."),
                PhraseItem("Artificial intelligence connects humanity.", "ar-ti-fi-shial in-te-li-djens", "A inteligência artificial conecta a humanidade.")
            )
        ),

        "de" to LanguageStudyPack(
            languageCode = "de",
            words = listOf(
                VocabularyItem("Hallo", "ha-lo", "Olá", "Saudações"),
                VocabularyItem("Danke", "dan-ke", "Obrigado", "Cortesia"),
                VocabularyItem("Bitte", "bi-te", "Por favor / De nada", "Cortesia"),
                VocabularyItem("Ja", "ia", "Sim", "Básico"),
                VocabularyItem("Nein", "nain", "Não", "Básico"),
                VocabularyItem("Freund", "froind", "Amigo", "Sociedade"),
                VocabularyItem("Familie", "fa-mi-lie", "Família", "Sociedade"),
                VocabularyItem("Wasser", "va-ser", "Água", "Alimentação"),
                VocabularyItem("Brot", "brot", "Pão", "Alimentação"),
                VocabularyItem("Zeit", "tsait", "Tempo", "Natureza"),
                VocabularyItem("Arbeit", "ar-bait", "Trabalho", "Sociedade"),
                VocabularyItem("Stadt", "shtat", "Cidade", "Locais"),
                VocabularyItem("Nacht", "naht", "Noite", "Tempo"),
                VocabularyItem("Welt", "velt", "Mundo", "Geral"),
                VocabularyItem("Herz", "herts", "Coração", "Corpo"),
                VocabularyItem("Sonne", "zo-ne", "Sol", "Natureza"),
                VocabularyItem("Straße", "shtra-se", "Rua", "Locais"),
                VocabularyItem("Geld", "guelt", "Dinheiro", "Economia"),
                VocabularyItem("Reise", "rai-ze", "Viagem", "Lazer"),
                VocabularyItem("Frieden", "fri-den", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("Guten Tag! Wie geht es Ihnen?", "gu-ten tak vi guet es i-nen", "Bom dia! Como está?"),
                PhraseItem("Guten Morgen allerseits.", "gu-ten mor-guen", "Bom dia a todos."),
                PhraseItem("Guten Abend und herzlich willkommen.", "gu-ten a-bent", "Boa tarde/noite e bem-vindo."),
                PhraseItem("Gute Nacht und schlaf gut.", "gu-te naht", "Boa noite e dorme bem."),
                PhraseItem("Sehr erfreut, Sie kennenzulernen.", "zer er-froyt", "Muito prazer em conhecê-lo."),
                PhraseItem("Wo ist der nächste Bahnhof?", "vo ist der nek-ste ban-hof", "Onde fica a estação mais próxima?"),
                PhraseItem("Wie viel kostet das bitte?", "vi fil kos-tet das", "Quanto custa isto, por favor?"),
                PhraseItem("Können Sie mir bitte helfen?", "kœ-nen zi mir hel-fen", "Pode ajudar-me, por favor?"),
                PhraseItem("Ich spreche nicht gut Deutsch.", "ih shpre-he niht gut doitsh", "Não falo bem alemão."),
                PhraseItem("Könnten Sie bitte langsamer sprechen?", "kœn-ten zi lang-za-mer shpre-hen", "Poderia falar mais devagar?"),
                PhraseItem("Das Essen schmeckt wunderbar!", "das e-sen shmekt", "A comida sabe maravilhosamente!"),
                PhraseItem("Die Rechnung bitte.", "di reh-nung bi-te", "A conta, por favor."),
                PhraseItem("Wie spät ist es jetzt?", "vi shpêt ist es", "Que horas são agora?"),
                PhraseItem("Das Wetter ist heute wunderschön.", "das ve-ter ist voon-der-shœn", "O tempo está magnífico hoje."),
                PhraseItem("Wo finde ich eine Apotheke?", "vo fin-de ih ai-ne a-po-te-ke", "Onde encontro uma farmácia?"),
                PhraseItem("Ich habe mich verirrt.", "ih ha-be mih fer-irt", "Estou perdido."),
                PhraseItem("Vielen Dank für Ihre Hilfe.", "fi-len dank", "Muito obrigado pela sua ajuda."),
                PhraseItem("Ein schönes Wochenende wünsche ich.", "ain shœ-nes vo-hen-en-de", "Desejo um bom fim de semana."),
                PhraseItem("Auf Wiedersehen und alles Gute!", "auf vi-der-ze-hen", "Adeus e tudo de bom!"),
                PhraseItem("Sprache verbindet Kulturen weltweit.", "shpra-he fer-bin-det", "A língua une culturas no mundo.")
            )
        ),

        "it" to LanguageStudyPack(
            languageCode = "it",
            words = listOf(
                VocabularyItem("Ciao", "tchau", "Olá / Adeus", "Saudações"),
                VocabularyItem("Grazie", "grat-tsie", "Obrigado", "Cortesia"),
                VocabularyItem("Per favore", "per fa-vo-re", "Por favor", "Cortesia"),
                VocabularyItem("Sì", "si", "Sim", "Básico"),
                VocabularyItem("No", "no", "Não", "Básico"),
                VocabularyItem("Amico", "a-mi-co", "Amigo", "Sociedade"),
                VocabularyItem("Famiglia", "fa-mi-lya", "Família", "Sociedade"),
                VocabularyItem("Acqua", "ak-kwa", "Água", "Alimentação"),
                VocabularyItem("Pane", "pa-ne", "Pão", "Alimentação"),
                VocabularyItem("Tempo", "tem-po", "Tempo", "Natureza"),
                VocabularyItem("Lavoro", "la-vo-ro", "Trabalho", "Sociedade"),
                VocabularyItem("Città", "tchi-ta", "Cidade", "Locais"),
                VocabularyItem("Notte", "no-te", "Noite", "Tempo"),
                VocabularyItem("Mondo", "mon-do", "Mundo", "Geral"),
                VocabularyItem("Cuore", "kwo-re", "Coração", "Corpo"),
                VocabularyItem("Sole", "so-le", "Sol", "Natureza"),
                VocabularyItem("Strada", "stra-da", "Rua / Estrada", "Locais"),
                VocabularyItem("Denaro", "de-na-ro", "Dinheiro", "Economia"),
                VocabularyItem("Viaggio", "vi-ad-jo", "Viagem", "Lazer"),
                VocabularyItem("Pace", "pa-tche", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("Ciao! Come stai oggi?", "tchau ko-me stai", "Olá! Como estás hoje?"),
                PhraseItem("Buongiorno a tutti quanti.", "bwon-djor-no", "Bom dia a toda a gente."),
                PhraseItem("Buonasera e benvenuti.", "bwo-na-se-ra", "Boa tarde/noite e bem-vindos."),
                PhraseItem("Buonanotte e sogni d'oro.", "bwo-na-not-te", "Boa noite e sonhos de ouro."),
                PhraseItem("Piacere di conoscerti.", "pya-tche-re", "Prazer em conhecer-te."),
                PhraseItem("Dov'è la stazione ferroviaria?", "do-vè la stat-tsyo-ne", "Onde fica a estação de comboios?"),
                PhraseItem("Quanto costa questo per favore?", "kwan-to kos-ta", "Quanto custa isto por favor?"),
                PhraseItem("Puoi aiutarmi un attimo?", "pwoi a-yu-tar-mi", "Podes ajudar-me um instante?"),
                PhraseItem("Non parlo bene l'italiano.", "non par-lo be-ne", "Não falo italiano fluentemente."),
                PhraseItem("Può parlare più lentamente?", "pwo par-la-re pyu len-ta-men-te", "Pode falar mais devagar?"),
                PhraseItem("Questo piatto è buonissimo!", "kwes-to pyat-to è bwo-nis-si-mo", "Este prato está ótimo!"),
                PhraseItem("Il conto per favore.", "il kon-to per fa-vo-re", "A conta por favor."),
                PhraseItem("Che ore sono adesso?", "ke o-re so-no", "Que horas são agora?"),
                PhraseItem("Che bella giornata di sole!", "ke bel-la djor-na-ta", "Que belo dia de sol!"),
                PhraseItem("Dove posso trovare una farmacia?", "do-ve pos-so tro-va-re", "Onde posso encontrar uma farmácia?"),
                PhraseItem("Mi sono perso, mi scusi.", "mi so-no per-so", "Perdi-me, desculpe."),
                PhraseItem("Grazie mille per la tua gentilezza.", "grat-tsie mil-le", "Muito obrigado pela tua gentileza."),
                PhraseItem("Buon fine settimana a tutti.", "bwon fi-ne set-ti-ma-na", "Bom fim de semana a todos."),
                PhraseItem("Arrivederci e a presto!", "ar-ri-ve-der-tchi", "Adeus e até breve!"),
                PhraseItem("L'arte e le parole uniscono i cuori.", "lar-te e le pa-ro-le", "A arte e as palavras unem corações.")
            )
        ),

        "ber" to LanguageStudyPack(
            languageCode = "ber",
            words = listOf(
                VocabularyItem("Azul", "a-zul", "Olá / Saudação", "Saudações"),
                VocabularyItem("Tanemmirt", "ta-nem-mirt", "Obrigado / Gratidão", "Cortesia"),
                VocabularyItem("Ihi", "i-hi", "Sim", "Básico"),
                VocabularyItem("Uhu", "u-hu", "Não", "Básico"),
                VocabularyItem("Ameddakel", "a-med-da-kel", "Amigo", "Sociedade"),
                VocabularyItem("Tawacult", "ta-wa-shult", "Família", "Sociedade"),
                VocabularyItem("Aman", "a-man", "Água", "Alimentação"),
                VocabularyItem("Aɣrum", "agh-rum", "Pão", "Alimentação"),
                VocabularyItem("Akud", "a-kud", "Tempo", "Natureza"),
                VocabularyItem("Tamurt", "ta-murt", "Terra / País", "Locais"),
                VocabularyItem("Iḍ", "idh", "Noite", "Tempo"),
                VocabularyItem("Ass", "ass", "Dia", "Tempo"),
                VocabularyItem("Tafukt", "ta-fukt", "Sol", "Natureza"),
                VocabularyItem("Agellid", "a-guel-lid", "Rei / Líder", "História"),
                VocabularyItem("Tamazight", "ta-ma-zight", "Língua Berbere", "Cultura"),
                VocabularyItem("Tudert", "tu-dert", "Vida", "Filosofia"),
                VocabularyItem("Tayri", "tay-ri", "Amor", "Sentimentos"),
                VocabularyItem("Talwit", "tal-wit", "Paz", "Sentimentos"),
                VocabularyItem("Abrid", "a-brid", "Caminho / Estrada", "Locais"),
                VocabularyItem("Idles", "id-les", "Cultura", "Cultura")
            ),
            phrases = listOf(
                PhraseItem("Azul fell-awen!", "a-zul fel-la-wen", "Olá a todos / Bem-vindos!"),
                PhraseItem("Amek telliḍ?", "a-mek tel-lidh", "Como estás?"),
                PhraseItem("Labas, tanemmirt!", "la-bas ta-nem-mirt", "Tudo bem, obrigado!"),
                PhraseItem("Ansuf yis-wen.", "an-suf yis-wen", "Sejam muito bem-vindos."),
                PhraseItem("Tanemmirt tameqqrant!", "ta-nem-mirt ta-mek-krant", "Muito obrigado!"),
                PhraseItem("Mani yella ubrid ɣer temdint?", "ma-ni yel-la ub-rid", "Onde fica o caminho para a cidade?"),
                PhraseItem("Acḥal i yeswa waya?", "ash-hal i yes-wa", "Quanto custa isto?"),
                PhraseItem("Tzemreḍ ad iyi-tɛawneḍ?", "tzem-redh ad i-yi te-aw-nedh", "Podes ajudar-me?"),
                PhraseItem("Ssarameɣ-ak afud igerrzen.", "sa-ra-megh a-fud i-ger-zen", "Desejo-te muito sucesso."),
                PhraseItem("Tamazight d tutlayt nneɣ.", "ta-ma-zight d tut-layt", "Tamazight é a nossa língua."),
                PhraseItem("Aman d tudert.", "a-man d tu-dert", "A água é vida."),
                PhraseItem("Talwit i umadal.", "tal-wit i u-ma-dal", "Paz para o mundo inteiro."),
                PhraseItem("Ass igerrzen i yal yiwen.", "ass i-ger-zen", "Um bom dia para todos."),
                PhraseItem("Iḍ ameggaz.", "idh a-meg-gaz", "Boa noite e bons sonhos."),
                PhraseItem("Anda teqqimeḍ?", "an-da tek-ki-medh", "Onde moras / ficas?"),
                PhraseItem("Ttmeslayeɣ cwiṭ kan.", "t-mes-la-yegh shwit", "Falo apenas um pouco."),
                PhraseItem("Qqim di talwit.", "kkim di tal-wit", "Fica em paz."),
                PhraseItem("Ar tufat!", "ar tu-fat", "Até à próxima / Até amanhã!"),
                PhraseItem("Nek d ameddakel nnek.", "nek d a-med-da-kel", "Eu sou teu amigo."),
                PhraseItem("Tidmi d tfelsit rennunt awal.", "tid-mi d tfel-sit", "A sabedoria enriquece as palavras.")
            )
        ),

        "ar" to LanguageStudyPack(
            languageCode = "ar",
            words = listOf(
                VocabularyItem("مرحباً (Marhaban)", "mar-ha-ban", "Olá / Bem-vindo", "Saudações"),
                VocabularyItem("شكراً (Shukran)", "shuk-ran", "Obrigado", "Cortesia"),
                VocabularyItem("من فضلك (Min fadlik)", "min fad-lik", "Por favor", "Cortesia"),
                VocabularyItem("نعم (Na'am)", "na-am", "Sim", "Básico"),
                VocabularyItem("لا (La)", "la", "Não", "Básico"),
                VocabularyItem("صديق (Sadeeq)", "sa-deek", "Amigo", "Sociedade"),
                VocabularyItem("عائلة ('A'ila)", "a-i-la", "Família", "Sociedade"),
                VocabularyItem("ماء (Ma')", "ma", "Água", "Alimentação"),
                VocabularyItem("خبز (Khubz)", "khubz", "Pão", "Alimentação"),
                VocabularyItem("وقت (Waqt)", "waqt", "Tempo", "Natureza"),
                VocabularyItem("عمل ('Amal)", "a-mal", "Trabalho", "Sociedade"),
                VocabularyItem("مدينة (Madina)", "ma-di-na", "Cidade", "Locais"),
                VocabularyItem("ليل (Layl)", "layl", "Noite", "Tempo"),
                VocabularyItem("عالم ('Alam)", "a-lam", "Mundo", "Geral"),
                VocabularyItem("قلب (Qalb)", "qalb", "Coração", "Corpo"),
                VocabularyItem("شمس (Shams)", "shams", "Sol", "Natureza"),
                VocabularyItem("شارع (Shari')", "sha-ri", "Rua", "Locais"),
                VocabularyItem("مال (Mal)", "mal", "Dinheiro", "Economia"),
                VocabularyItem("سفر (Safar)", "sa-far", "Viagem", "Lazer"),
                VocabularyItem("سلام (Salam)", "sa-lam", "Paz", "Sentimentos")
            ),
            phrases = listOf(
                PhraseItem("السلام عليكم (Assalamu Alaikum)", "as-sa-la-mu a-lai-kum", "A paz esteja convosco / Olá"),
                PhraseItem("صباح الخير (Sabah al-khair)", "sa-bah al-khair", "Bom dia"),
                PhraseItem("مساء الخير (Masa' al-khair)", "ma-sa al-khair", "Boa tarde / Boa noite"),
                PhraseItem("تصبح على خير (Tisbah 'ala khair)", "tis-bah a-la khair", "Boa noite / Bons sonhos"),
                PhraseItem("تشرفت بمعرفتك (Tasharraftu bima'rifatik)", "ta-shar-raf-tu", "Muito prazer em conhecê-lo"),
                PhraseItem("أين محطة القطار؟ (Ayna mahattat al-qitar?)", "ay-na ma-hat-tat", "Onde fica a estação de comboios?"),
                PhraseItem("كم يكلف هذا؟ (Kam yukallifu hadha?)", "kam yu-kal-li-fu", "Quanto custa isto?"),
                PhraseItem("هل يمكنك مساعدتي؟ (Hal yumkinuka musa'adati?)", "hal yum-ki-nu-ka", "Podes ajudar-me?"),
                PhraseItem("أنا لا أتكلم العربية بطلاقة (Ana la atakallam...)", "a-na la a-ta-kal-lam", "Não falo árabe fluentemente"),
                PhraseItem("تكلم ببطء من فضلك (Takallam bibut')", "ta-kal-lam bi-but", "Fala mais devagar, por favor"),
                PhraseItem("الطعام لذيذ جداً (At-ta'am ladhidh jiddan)", "at-ta-am la-dhidh", "A comida está muito saborosa"),
                PhraseItem("الحساب من فضلك (Al-hisab min fadlik)", "al-hi-sab", "A conta, por favor"),
                PhraseItem("كم الساعة الآن؟ (Kam as-sa'ah al-an?)", "kam as-sa-ah", "Que horas são agora?"),
                PhraseItem("الجو جميل اليوم (Al-jawwu jameel al-yawm)", "al-jaw-wu ja-mil", "O tempo está lindo hoje"),
                PhraseItem("أين أجد صيدلية؟ (Ayna ajidu saydaliyyah?)", "ay-na a-ji-du", "Onde encontro uma farmácia?"),
                PhraseItem("أنا ضائع، ساعدني (Ana da'i', sa'idni)", "a-na da-i", "Estou perdido, ajuda-me"),
                PhraseItem("شكراً جزيلاً لك (Shukran jazeelan lak)", "shuk-ran ja-zi-lan", "Muito obrigado pela gentileza"),
                PhraseItem("أتمنى لك يوماً سعيداً (Atamanna laka yawman sa'eedan)", "a-ta-man-na lak", "Desejo-te um dia feliz"),
                PhraseItem("مع السلامة وإلى اللقاء (Ma'a as-salamah)", "ma-as-sa-la-mah", "Fica com Deus / Até logo"),
                PhraseItem("السلام والمحبة لجميع الشعوب (As-salam wal-mahabbah)", "as-sa-lam wal-ma-hab-bah", "Paz e amor para todos os povos")
            )
        )
    )

    private fun defaultPack(code: String): LanguageStudyPack {
        val meta = SupportedLanguages.findByCode(code) ?: SupportedLanguages.ALL.first()
        return LanguageStudyPack(
            languageCode = meta.code,
            words = listOf(
                VocabularyItem(meta.sampleGreeting.split(" ").first(), "", "Saudação inicial", "Saudações"),
                VocabularyItem("Paz / Harmonia", "", "Conceito de tranquilidade", "Sentimentos"),
                VocabularyItem("Obrigado", "", "Expressão de gratidão", "Cortesia"),
                VocabularyItem("Por favor", "", "Pedido cortês", "Cortesia"),
                VocabularyItem("Sim", "", "Confirmação positiva", "Básico"),
                VocabularyItem("Não", "", "Negação", "Básico"),
                VocabularyItem("Amigo", "", "Pessoa de confiança", "Sociedade"),
                VocabularyItem("Família", "", "Núcleo familiar", "Sociedade"),
                VocabularyItem("Água", "", "Líquido vital", "Alimentação"),
                VocabularyItem("Pão / Alimento", "", "Sustento", "Alimentação"),
                VocabularyItem("Tempo", "", "Hora ou clima", "Natureza"),
                VocabularyItem("Trabalho", "", "Atividade profissional", "Sociedade"),
                VocabularyItem("Cidade", "", "Localidade", "Locais"),
                VocabularyItem("Mundo", "", "Universo / Terra", "Geral"),
                VocabularyItem("Coração", "", "Vida e afeto", "Corpo"),
                VocabularyItem("Sol", "", "Astro da luz", "Natureza"),
                VocabularyItem("Noite", "", "Período noturno", "Tempo"),
                VocabularyItem("Dia", "", "Período diurno", "Tempo"),
                VocabularyItem("Viagem", "", "Deslocamento", "Lazer"),
                VocabularyItem("Cultura", "", "Identidade do povo", "Cultura")
            ),
            phrases = listOf(
                PhraseItem(meta.sampleGreeting, "", "Saudação típica no idioma"),
                PhraseItem("Bom dia a todos!", "", "Cumprimento matinal"),
                PhraseItem("Boa tarde e bem-vindos.", "", "Cumprimento vespertino"),
                PhraseItem("Boa noite e bons sonhos.", "", "Despedida noturna"),
                PhraseItem("Muito prazer em conhecê-lo.", "", "Ao ser apresentado"),
                PhraseItem("Onde posso encontrar auxílio?", "", "A pedir informação"),
                PhraseItem("Quanto custa isto, por favor?", "", "Comércio"),
                PhraseItem("Pode ajudar-me um momento?", "", "Auxílio"),
                PhraseItem("Estou a aprender esta língua.", "", "Aprendizagem"),
                PhraseItem("Poderia falar um pouco mais devagar?", "", "Compreensão"),
                PhraseItem("A comida está magnífica!", "", "Elogio culinário"),
                PhraseItem("A conta, por favor.", "", "Restauração"),
                PhraseItem("Que horas são neste momento?", "", "Horário"),
                PhraseItem("Está um dia excelente hoje.", "", "Clima"),
                PhraseItem("Onde fica a estação de comboios?", "", "Transportes"),
                PhraseItem("Muito obrigado pela sua hospitalidade.", "", "Gratidão"),
                PhraseItem("Tenha um ótimo fim de semana.", "", "Votos"),
                PhraseItem("Até breve e cuide-se bem.", "", "Despedida"),
                PhraseItem("A voz conecta todas as culturas.", "", "Universalidade"),
                PhraseItem("Paz e prosperidade para o mundo.", "", "Mensagem final")
            )
        )
    }
}
